### ISSUE TITLE
g.scalar does not support optional()

### ISSUE THREAD

**Issue by Malvolio** [stepci/garph#82]
There does not seem to be any way to mark a custom scalar as optional.

**Comment by mishushakov** [comment]
Can you give me an example?

**Comment by Malvolio** [comment]
The definition of a scalar is

```
declare class GScalar<I, O> extends Type<I, 'Scalar'> {
    _output: O;
    constructor(name: string, scalarOptions?: ScalarOptions<I, O>);
    specifiedByUrl(url: string): this;
}
```

so naturally if you do this:

```
export cons Date = g.scalarType<Date, string>("Date", {
  serialize: (value) => formatISO(value),
  parseValue: (value) => new Date(value),
});

export const Task = g.type("Task", {
  name: g.string(),
  due: Date.optional(),
});

```

If I do this:
export const Task = g.type("Task", {
  name: g.string(),
  due: g.ref(() => Date).optional(),
});

```
it *does* compile (and work) but I don’t know if that is what I should be doing.

**Comment by m1212e** [comment]
Hi, sorry to warm this up again, but optional support on scalars would be cool nonetheless. I'm currently writing a prisma generator to create garph types based on prisma types. The code generator inlines scalar types for Date and JSON fields which are not natively supported by GraphQL. An example might look like this:

```ts
import { g } from "garph";
export const Conference = g.type("Conference", {
  id: g.id().required(),
  name: g.string().required(),
  committees: g.ref(Committee).list().required(),
  start: g
    .scalarType<Date, number>("Date", {
      serialize: (value) => value.getTime(),
      parseValue: (value) => new Date(value),
    })
    .optional(),
  end: g
    .scalarType<Date, number>("Date", {
      serialize: (value) => value.getTime(),
      parseValue: (value) => new Date(value),
    })
    .optional(),
  delegations: g.ref(Delegation).list().required(),
  members: g.ref(ConferenceMember).list().required(),
});

```

This is invalid since neither optional nor required exist on the scalars. Externally defining these types and using ref would be possible but complicate the whole thing. @mishushakov do you plan on supporting this?

Would a workaround like this:

```ts
  start: g
    .ref(
      g.scalarType<Date, number>("Date", {
        serialize: (value) => value.getTime(),
        parseValue: (value) => new Date(value),
      })
    )
    .optional(),
```
cause a lot of overhead/boilerplate?

**Comment by mishushakov** [comment]
You can submit a pull request? At the time, I don't think we should be supporting inlining types

**Comment by m1212e** [comment]
Ok, thanks for the quick response!
